# Don't change these
theme: jekyll-theme-primer
spec_server: specs.amwa.tv

# AMWA ID
amwa_id: BCP-002

# Base name for site (typically lower case version of AMWA ID, or the repo name)
baseurl: /bcp-002

# Which release or branch appears in header links and on the home page
default_tree: branches/master # alternatively e.g. releases/v1.0

# Regex patterns of releases and branches to show
show_releases:
show_branches: master
